### ISSUE TITLE
"The truth about shared" - still the truth?

### ISSUE THREAD

**Issue by andrej-petrovic** [p0nce/d-idioms#164]
The idiom ["The Truth About Shared"](https://p0nce.github.io/d-idioms/#The-truth-about-shared) says that shared is unimplemented. I was under the impression that it's implemented, and I've definitely had to use it in thread-safe code. It looks like that idiom was last update in 2015, so I'm guessing it's out of date?

**Comment by p0nce** [comment]
I don't think things have changed.
In last DConf Alexandrescu said "we need the champion of shared" to change it to do something 
sensible. Well, focus has moved elsewhere instead of "shared".

Of course shared the type constructor does "work", it's just not particularly useful and a considerable distraction for those actually writing multithreaded code.
